# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vtouffet <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/07/16 11:29:04 by vtouffet          #+#    #+#              #
#    Updated: 2017/07/16 12:53:27 by vtouffet         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=do-op
SRCS=srcs/do_op.c srcs/ft_atoi.c srcs/ft_add.c srcs/ft_div.c srcs/ft_mod.c srcs/ft_mul.c srcs/ft_sub.c

all:
	gcc $(SRCS) -o $(NAME)

clean:
	/bin/rm -f $(NAME)

re: clean all
