# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vtouffet <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/07/18 21:20:35 by vtouffet          #+#    #+#              #
#    Updated: 2017/07/20 11:40:42 by vtouffet         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=ft_tail
SRCS=srcs/*.c

all:
	@gcc $(SRCS) -o $(NAME)

clean:
	@/bin/rm -f *.o

fclean: clean
	@/bin/rm -f $(NAME)

re: fclean re
